@echo off
REM SmartSpending Setup Script for Windows
REM This script automates the setup process for the SmartSpending application

echo ================================================
echo   SmartSpending - Setup Script (Windows)
echo   Version 2.0.0
echo ================================================
echo.

REM Configuration
set DB_NAME=quan_ly_chi_tieu
set DB_USER=root
set DB_PASS=
set DB_HOST=localhost
set MYSQL_PATH=C:\xampp\mysql\bin\mysql.exe

REM Check if MySQL exists
echo Checking MySQL installation...
if exist "%MYSQL_PATH%" (
    echo [OK] MySQL found at %MYSQL_PATH%
) else (
    echo [ERROR] MySQL not found at %MYSQL_PATH%
    echo Please update MYSQL_PATH variable in this script
    pause
    exit /b 1
)

REM Check PHP
echo Checking PHP installation...
php -v >nul 2>&1
if %errorlevel%==0 (
    echo [OK] PHP is installed
) else (
    echo [ERROR] PHP not found in PATH
    echo Please add PHP to your PATH environment variable
    pause
    exit /b 1
)

echo.
echo ================================================
echo   Database Configuration
echo ================================================
echo.

REM Get database credentials
set /p input_host="Database host [localhost]: "
if not "%input_host%"=="" set DB_HOST=%input_host%

set /p input_db="Database name [quan_ly_chi_tieu]: "
if not "%input_db%"=="" set DB_NAME=%input_db%

set /p input_user="Database user [root]: "
if not "%input_user%"=="" set DB_USER=%input_user%

set /p DB_PASS="Database password: "

echo.
echo Creating database '%DB_NAME%'...
if "%DB_PASS%"=="" (
    "%MYSQL_PATH%" -h %DB_HOST% -u %DB_USER% -e "CREATE DATABASE IF NOT EXISTS %DB_NAME% CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"
) else (
    "%MYSQL_PATH%" -h %DB_HOST% -u %DB_USER% -p%DB_PASS% -e "CREATE DATABASE IF NOT EXISTS %DB_NAME% CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"
)

if %errorlevel%==0 (
    echo [OK] Database created
) else (
    echo [ERROR] Failed to create database
    pause
    exit /b 1
)

echo.
echo Importing base schema...
if "%DB_PASS%"=="" (
    "%MYSQL_PATH%" -h %DB_HOST% -u %DB_USER% %DB_NAME% < database\quan_ly_chi_tieu.sql
) else (
    "%MYSQL_PATH%" -h %DB_HOST% -u %DB_USER% -p%DB_PASS% %DB_NAME% < database\quan_ly_chi_tieu.sql
)

if %errorlevel%==0 (
    echo [OK] Schema imported
) else (
    echo [ERROR] Failed to import schema
    pause
    exit /b 1
)

echo.
echo Running migrations...
if "%DB_PASS%"=="" (
    "%MYSQL_PATH%" -h %DB_HOST% -u %DB_USER% %DB_NAME% < database\migrations\001_add_recurring_and_budgets.sql
) else (
    "%MYSQL_PATH%" -h %DB_HOST% -u %DB_USER% -p%DB_PASS% %DB_NAME% < database\migrations\001_add_recurring_and_budgets.sql
)

if %errorlevel%==0 (
    echo [OK] Migrations completed
) else (
    echo [ERROR] Failed to run migrations
    pause
    exit /b 1
)

REM Ask about sample data
echo.
set /p import_sample="Do you want to import sample data? (y/n): "
if /i "%import_sample%"=="y" (
    echo Importing sample data...
    if "%DB_PASS%"=="" (
        "%MYSQL_PATH%" -h %DB_HOST% -u %DB_USER% %DB_NAME% < database\sample_data_october_2025.sql
    ) else (
        "%MYSQL_PATH%" -h %DB_HOST% -u %DB_USER% -p%DB_PASS% %DB_NAME% < database\sample_data_october_2025.sql
    )
    
    if %errorlevel%==0 (
        echo [OK] Sample data imported
    ) else (
        echo [WARNING] Failed to import sample data (optional)
    )
)

REM Update config file
echo.
echo Updating configuration file...
(
    echo ^<?php
    echo /**
    echo  * Database Configuration
    echo  * Generated by setup script on %date% %time%
    echo  */
    echo.
    echo define('DB_HOST', '%DB_HOST%'^);
    echo define('DB_NAME', '%DB_NAME%'^);
    echo define('DB_USER', '%DB_USER%'^);
    echo define('DB_PASS', '%DB_PASS%'^);
    echo define('DB_CHARSET', 'utf8mb4'^);
    echo.
    echo // Uncomment for development error reporting
    echo // error_reporting(E_ALL^);
    echo // ini_set('display_errors', 1^);
) > config\database.php

if %errorlevel%==0 (
    echo [OK] Configuration updated
) else (
    echo [ERROR] Failed to update configuration
    pause
    exit /b 1
)

REM Check for Composer
echo.
echo Checking for Composer...
composer --version >nul 2>&1
if %errorlevel%==0 (
    echo [OK] Composer found
    echo Running composer dump-autoload...
    composer dump-autoload -o
    echo [OK] Autoload generated
) else (
    echo [WARNING] Composer not found (optional)
    echo You may need to run 'composer dump-autoload' manually
)

REM Completion
echo.
echo ================================================
echo   Setup Complete! 
echo ================================================
echo.
echo Next steps:
echo 1. Start XAMPP (Apache and MySQL)
echo 2. Access the application:
echo    - http://localhost/Quan_Ly_Chi_Tieu/public
echo    - Or configure a virtual host
echo.

if /i "%import_sample%"=="y" (
    echo 3. Login with sample account:
    echo    - Username: testuser
    echo    - Password: password123
    echo.
)

echo Documentation:
echo   - README: README_NEW.md
echo   - API Docs: docs\API.md
echo   - Migration Guide: docs\MIGRATION_GUIDE.md
echo.
echo Support:
echo   - GitHub: https://github.com/HuyHoangI4t/Quan_Ly_Chi_Tieu
echo   - Email: huyhoangpro187@gmail.com
echo.
echo Thank you for using SmartSpending!
echo.
pause
