#!/bin/bash

# SmartSpending Setup Script
# This script automates the setup process for the SmartSpending application

echo "================================================"
echo "  SmartSpending - Setup Script"
echo "  Version 2.0.0"
echo "================================================"
echo ""

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
DB_NAME="quan_ly_chi_tieu"
DB_USER="root"
DB_PASS=""
DB_HOST="localhost"

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check PHP
echo -n "Checking PHP installation... "
if command_exists php; then
    PHP_VERSION=$(php -v | head -n 1 | cut -d " " -f 2 | cut -d "." -f 1,2)
    echo -e "${GREEN}✓${NC} PHP $PHP_VERSION"
else
    echo -e "${RED}✗${NC} PHP not found"
    echo "Please install PHP 7.4 or higher"
    exit 1
fi

# Check MySQL
echo -n "Checking MySQL installation... "
if command_exists mysql; then
    echo -e "${GREEN}✓${NC} MySQL installed"
else
    echo -e "${RED}✗${NC} MySQL not found"
    echo "Please install MySQL 5.7+ or MariaDB 10.4+"
    exit 1
fi

# Check Composer
echo -n "Checking Composer installation... "
if command_exists composer; then
    echo -e "${GREEN}✓${NC} Composer installed"
    COMPOSER_AVAILABLE=true
else
    echo -e "${YELLOW}⚠${NC} Composer not found (optional)"
    COMPOSER_AVAILABLE=false
fi

echo ""
echo "================================================"
echo "  Database Configuration"
echo "================================================"
echo ""

# Get database credentials
read -p "Database host [localhost]: " input_host
DB_HOST=${input_host:-$DB_HOST}

read -p "Database name [quan_ly_chi_tieu]: " input_db
DB_NAME=${input_db:-$DB_NAME}

read -p "Database user [root]: " input_user
DB_USER=${input_user:-$DB_USER}

read -sp "Database password: " input_pass
DB_PASS=$input_pass
echo ""

# Test database connection
echo -n "Testing database connection... "
if mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" -e ";" 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Connection successful"
else
    echo -e "${RED}✗${NC} Connection failed"
    echo "Please check your credentials and try again"
    exit 1
fi

# Create database
echo -n "Creating database '$DB_NAME'... "
if mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" -e "CREATE DATABASE IF NOT EXISTS $DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;" 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Database created"
else
    echo -e "${RED}✗${NC} Failed to create database"
    exit 1
fi

# Import base schema
echo -n "Importing base schema... "
if mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" < database/quan_ly_chi_tieu.sql 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Schema imported"
else
    echo -e "${RED}✗${NC} Failed to import schema"
    exit 1
fi

# Import migrations
echo -n "Running migrations... "
if mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" < database/migrations/001_add_recurring_and_budgets.sql 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Migrations completed"
else
    echo -e "${RED}✗${NC} Failed to run migrations"
    exit 1
fi

# Ask about sample data
echo ""
read -p "Do you want to import sample data? (y/n): " import_sample
if [ "$import_sample" = "y" ] || [ "$import_sample" = "Y" ]; then
    echo -n "Importing sample data... "
    if mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" < database/sample_data_october_2025.sql 2>/dev/null; then
        echo -e "${GREEN}✓${NC} Sample data imported"
    else
        echo -e "${YELLOW}⚠${NC} Failed to import sample data (optional)"
    fi
fi

# Update config file
echo -n "Updating configuration file... "
cat > config/database.php << EOF
<?php
/**
 * Database Configuration
 * Generated by setup script on $(date)
 */

define('DB_HOST', '$DB_HOST');
define('DB_NAME', '$DB_NAME');
define('DB_USER', '$DB_USER');
define('DB_PASS', '$DB_PASS');
define('DB_CHARSET', 'utf8mb4');

// Uncomment for development error reporting
// error_reporting(E_ALL);
// ini_set('display_errors', 1);
EOF

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓${NC} Configuration updated"
else
    echo -e "${RED}✗${NC} Failed to update configuration"
    exit 1
fi

# Run Composer if available
if [ "$COMPOSER_AVAILABLE" = true ]; then
    echo ""
    echo "================================================"
    echo "  Installing Dependencies"
    echo "================================================"
    echo ""
    composer dump-autoload -o
    echo -e "${GREEN}✓${NC} Autoload generated"
fi

# Set permissions
echo ""
echo "================================================"
echo "  Setting Permissions"
echo "================================================"
echo ""

if [ -d "vendor" ]; then
    chmod -R 755 vendor
    echo -e "${GREEN}✓${NC} Vendor directory permissions set"
fi

if [ -d "public" ]; then
    chmod -R 755 public
    echo -e "${GREEN}✓${NC} Public directory permissions set"
fi

# Completion
echo ""
echo "================================================"
echo "  Setup Complete! 🎉"
echo "================================================"
echo ""
echo "Next steps:"
echo "1. Start your web server (Apache/Nginx)"
echo "2. Access the application:"
echo "   - http://localhost/Quan_Ly_Chi_Tieu/public"
echo "   - Or configure a virtual host"
echo ""

if [ "$import_sample" = "y" ] || [ "$import_sample" = "Y" ]; then
    echo "3. Login with sample account:"
    echo "   - Username: testuser"
    echo "   - Password: password123"
    echo ""
fi

echo "Documentation:"
echo "  - README: README_NEW.md"
echo "  - API Docs: docs/API.md"
echo "  - Migration Guide: docs/MIGRATION_GUIDE.md"
echo ""
echo "Support:"
echo "  - GitHub: https://github.com/HuyHoangI4t/Quan_Ly_Chi_Tieu"
echo "  - Email: huyhoangpro187@gmail.com"
echo ""
echo "Thank you for using SmartSpending! 💰✨"
echo ""
